# Generated by Django 5.2.6 on 2025-09-14 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkovChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=2)),
                ('transition_matrix', models.JSONField(default=dict)),
                ('states', models.JSONField(default=list)),
                ('state_mapping', models.JSONField(default=dict)),
                ('training_samples', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_trained', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarkovAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transition_probabilities', models.JSONField(default=dict)),
                ('state_sequence', models.JSONField(default=list)),
                ('pattern_likelihood', models.FloatField(default=0.0)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('separation_quality', models.FloatField(default=0.0)),
                ('confidence_interval', models.JSONField(default=dict)),
                ('statistical_significance', models.FloatField(default=0.0)),
                ('analysis_duration', models.FloatField(default=0.0)),
                ('markov_order_used', models.IntegerField(default=2)),
                ('feature_extraction_method', models.CharField(default='mfcc', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markov_analyses', to='audio_processor.audiofile')),
                ('separated_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio_processor.separatedtrack')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=255)),
                ('instrument_label', models.CharField(max_length=50)),
                ('feature_vector', models.JSONField(default=list)),
                ('ground_truth', models.JSONField(default=dict)),
                ('sample_quality', models.FloatField(default=0.0)),
                ('noise_level', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('markov_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='markov_models.markovchain')),
            ],
        ),
        migrations.CreateModel(
            name='AudioPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('spectral', 'Spectral Pattern'), ('temporal', 'Temporal Pattern'), ('harmonic', 'Harmonic Pattern'), ('rhythmic', 'Rhythmic Pattern'), ('timbral', 'Timbral Pattern')], max_length=20)),
                ('pattern_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('entropy', models.FloatField(default=0.0)),
                ('complexity', models.FloatField(default=0.0)),
                ('predictability', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='audio_processor.audiofile')),
                ('markov_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='markov_models.markovchain')),
            ],
            options={
                'unique_together': {('audio_file', 'pattern_type')},
            },
        ),
        migrations.CreateModel(
            name='SeparationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('vocals', 'Vocals'), ('drums', 'Drums'), ('bass', 'Bass'), ('piano', 'Piano'), ('guitar', 'Guitar'), ('strings', 'Strings'), ('brass', 'Brass'), ('woodwinds', 'Woodwinds'), ('other', 'Other')], max_length=20)),
                ('separation_threshold', models.FloatField(default=0.5)),
                ('noise_reduction_factor', models.FloatField(default=0.1)),
                ('spectral_smoothing', models.FloatField(default=0.2)),
                ('separation_accuracy', models.FloatField(default=0.0)),
                ('snr_improvement', models.FloatField(default=0.0)),
                ('processing_speed', models.FloatField(default=0.0)),
                ('training_files_count', models.IntegerField(default=0)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('markov_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_models', to='markov_models.markovchain')),
            ],
            options={
                'unique_together': {('instrument_type', 'markov_chain')},
            },
        ),
    ]
