# Generated by Django 5.2.6 on 2025-09-15 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processor', '0002_alter_audioproject_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioproject',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
