# Generated by Django 5.2.6 on 2025-09-14 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('root_note', models.CharField(max_length=2)),
                ('chord_type', models.CharField(max_length=20)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('notes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChordProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chords', models.JSONField()),
                ('key', models.CharField(max_length=10)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('tempo', models.IntegerField(default=120)),
                ('difficulty_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='instruments/')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_skill_level', models.IntegerField(default=3)),
                ('estimated_duration', models.DurationField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathChord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.chord')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.learningpath')),
            ],
        ),
        migrations.AddField(
            model_name='learningpath',
            name='chords',
            field=models.ManyToManyField(through='music_theory.LearningPathChord', to='music_theory.chord'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
                ('tempo', models.IntegerField(default=120)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('audio_file', models.FileField(blank=True, upload_to='songs/')),
                ('lyrics', models.TextField(blank=True)),
                ('tabs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chord_progression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_theory.chordprogression')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('tempo_achieved', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('recorded_audio', models.FileField(blank=True, upload_to='practice_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_theory.chord')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_theory.song')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.learningpath')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.song')),
            ],
        ),
        migrations.AddField(
            model_name='learningpath',
            name='songs',
            field=models.ManyToManyField(through='music_theory.LearningPathSong', to='music_theory.song'),
        ),
        migrations.CreateModel(
            name='InstrumentChord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingering', models.JSONField()),
                ('difficulty_level', models.IntegerField(default=1)),
                ('alternative_fingerings', models.JSONField(default=list)),
                ('audio_sample', models.FileField(blank=True, upload_to='chord_samples/')),
                ('diagram_image', models.ImageField(blank=True, upload_to='chord_diagrams/')),
                ('chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.chord')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.instrument')),
            ],
            options={
                'unique_together': {('instrument', 'chord')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(default=1)),
                ('practice_time', models.DurationField(default='00:00:00')),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('chord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_theory.chord')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_theory.instrument')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_theory.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'instrument', 'song', 'chord')},
            },
        ),
    ]
